### ISSUE TITLE
Not working with Typescript

### ISSUE THREAD

**Issue by alanpy** [nicklayb/react-auth-guard#12]
I have tried to use this on a typescript app but it could not install the dev types, i have tried to use npm install `@types/react-auth-guard -D` but no success.

i don't now if i have make some mistakes or is there another way to install for typescript support.

**Comment by nicklayb** [comment]
Yeah I did not include any typings for it. I'm not super familiar with typescript but I think you should be able to define typings in your project. I'm not planning on writing those, especially because a design decision (which I'm no more proud of) made typing difficult (the getters). My plan is to remove the getter support and just let you make your own functions that receives the authprovider payload
